### ISSUE TITLE
How do I get a secret key

### ISSUE THREAD

**Issue by shivakrishna9** [cassac/recruit#1]
Seems like Secret key is required to run the application.

**Comment by cassac** [comment]
Referring to https://github.com/cassac/recruit/blob/master/recruit/settings.py#L23 In a production application you would need to take extra precautions, but for now you can replace `os.environ['SECRET_KEY']` with a random string. Read about the `SECRET_KEY` here https://docs.djangoproject.com/en/1.10/ref/settings/#secret-key
