### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by datatalking** [cassac/recruit#3]
can you post a screenshot of what this application looks like?

Perhaps it runs headless in a terminal if so screenshot that.

I'm interested in contributing as well as using this.

**Comment by cassac** [comment]
Thanks for taking interest in my web app. Unfortunately, I don't have any screenshots of this and don't have this app working on my local machine. Feel free to fork this repo.

**Comment by datatalking** [comment]
What current does work as I have a potential need for this.

**Comment by cassac** [comment]
@datatalking It _should_ work with the older dependencies, but you'd want to update them and I'm unsure if there would be any breakage during that process.
